/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import connection.InsertData;
import connection.LoadData;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import model.ChuyenBay;
import model.Ghe;
import model.HoaDon;
import model.Ve;

/**
 *
 * @author t0168
 */
public class GiaoDienHoaDonMotChieu extends javax.swing.JFrame {

    /**
     * Creates new form BillFrame
     */
    DefaultTableModel dtm;
    DefaultTableModel dtm2;
    private Date ngayHienTai;
    private int phanTramGiaThuongGia = 2;
    private int giaCoBan = 0;
    private int soVePhoThong = 0;
    private int soVeThuongGia = 0;
    private int tongTien;
    
    private String maHoaDon;
    private String maChuyenBayDi;
    private ArrayList<Ve> danhSachVe;

    public GiaoDienHoaDonMotChieu(String maHoaDon, ArrayList<Ve> danhSachVe, String maChuyenBayDi) {
        initComponents();
        this.danhSachVe = danhSachVe;
        this.maHoaDon = maHoaDon;
        this.maChuyenBayDi = maChuyenBayDi;
        dtm = (DefaultTableModel) jTable_VeDaChon.getModel();
        dtm.setColumnIdentifiers(new Object[]{
            "MaVe", "SDTKhachHang", "MaChuyenBay", "Gia", "KyGui", "TrangThaiDoi", "TrangThaiVe",
            "CMNDNguoiBay", "TenNguoiBay", "EmailNguoiBay", "SDTNguoiBay", "MaHoaDon", "MaGhe"
        });

        dtm2 = (DefaultTableModel) jTable_ChuyenBayDaChon.getModel();
        dtm2.setColumnIdentifiers(new Object[]{
            "MaChuyenBay", "MaMayBay", "MaSanBayDi", "MaSanBayDen", "NgayBay", "GioBay", "GhiChu",
            "KhoangCach"
        });

        String date = new SimpleDateFormat("dd/MM/yyyy").format(Calendar.getInstance().getTime());
        try {
            ngayHienTai = new SimpleDateFormat("dd/MM/yyyy").parse(date);
        } catch (ParseException ex) {
            Logger.getLogger(GiaoDienTimChuyenBay.class.getName()).log(Level.SEVERE, null, ex);
        }
        jDateChooser_NgayXuatHoaDon.setDate(ngayHienTai);
        jDateChooser_NgayXuatHoaDon.setEnabled(false);

        hienThongTin();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel_IconMayBay = new javax.swing.JLabel();
        jLabel_HPT = new javax.swing.JLabel();
        jLabel_AirLines = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel_SoDienThoaiKhachHang = new javax.swing.JLabel();
        jTextField_SoDienThoaiKhachHang = new javax.swing.JTextField();
        jLabel_TenKhachHang = new javax.swing.JLabel();
        jTextField_TenKhachHang = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_ChuyenBayDaChon = new javax.swing.JTable();
        jLabel_ChuyenBayDaChon = new javax.swing.JLabel();
        jLabel_PhoThong = new javax.swing.JLabel();
        jTextField_SLVePhoThong = new javax.swing.JTextField();
        jLabel_ThuongGia = new javax.swing.JLabel();
        jTextField_SLVeThuongGia = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField_GiaVePhoThong = new javax.swing.JTextField();
        jTextField_GiaVeThuongGia = new javax.swing.JTextField();
        jLabel_NgayXuatHoaDon = new javax.swing.JLabel();
        jDateChooser_NgayXuatHoaDon = new com.toedter.calendar.JDateChooser();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField_TongTien = new javax.swing.JTextField();
        jLabel_TongTien = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_VeDaChon = new javax.swing.JTable();
        jLabel_VeDaChon = new javax.swing.JLabel();
        jButton_HoanTatHoaDon = new javax.swing.JButton();
        jButton_ThoatGiaoDienHoaDon = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(48, 57, 82));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jLabel_IconMayBay.setForeground(new java.awt.Color(204, 255, 255));
        jLabel_IconMayBay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/icons8_airplane_48px_4.png"))); // NOI18N

        jLabel_HPT.setFont(new java.awt.Font("Roboto Mono Light", 1, 48)); // NOI18N
        jLabel_HPT.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_HPT.setText("HPT");

        jLabel_AirLines.setFont(new java.awt.Font("Roboto Light", 1, 24)); // NOI18N
        jLabel_AirLines.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_AirLines.setText("AIRLINES™");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel_IconMayBay)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel_HPT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_AirLines, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel_HPT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel_AirLines, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel_IconMayBay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(89, 98, 117));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jLabel_SoDienThoaiKhachHang.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel_SoDienThoaiKhachHang.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_SoDienThoaiKhachHang.setText("Mã Khách Hàng");

        jLabel_TenKhachHang.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel_TenKhachHang.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_TenKhachHang.setText("Tên Khách Hàng");

        jTable_ChuyenBayDaChon.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jTable_ChuyenBayDaChon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable_ChuyenBayDaChon.setGridColor(new java.awt.Color(0, 0, 0));
        jTable_ChuyenBayDaChon.setIntercellSpacing(new java.awt.Dimension(0, 0));
        jTable_ChuyenBayDaChon.setRowHeight(30);
        jTable_ChuyenBayDaChon.setSelectionBackground(new java.awt.Color(255, 77, 77));
        jTable_ChuyenBayDaChon.setShowVerticalLines(false);
        jTable_ChuyenBayDaChon.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable_ChuyenBayDaChon);
        jTable_ChuyenBayDaChon.getAccessibleContext().setAccessibleName("");

        jLabel_ChuyenBayDaChon.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel_ChuyenBayDaChon.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_ChuyenBayDaChon.setText("Chuyến bay đã chọn");

        jLabel_PhoThong.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel_PhoThong.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_PhoThong.setText("Phổ thông");

        jLabel_ThuongGia.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel_ThuongGia.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_ThuongGia.setText("Thương gia");

        jLabel10.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("x");

        jLabel11.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("x");

        jLabel_NgayXuatHoaDon.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel_NgayXuatHoaDon.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_NgayXuatHoaDon.setText("Ngày xuất hóa đơn");

        jDateChooser_NgayXuatHoaDon.setDateFormatString("dd/MM/yyyy");

        jLabel13.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("+");

        jLabel14.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("=");

        jLabel_TongTien.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel_TongTien.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_TongTien.setText("Tổng tiền");

        jTable_VeDaChon.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jTable_VeDaChon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable_VeDaChon.setGridColor(new java.awt.Color(0, 0, 0));
        jTable_VeDaChon.setIntercellSpacing(new java.awt.Dimension(0, 0));
        jTable_VeDaChon.setRowHeight(30);
        jTable_VeDaChon.setSelectionBackground(new java.awt.Color(255, 77, 77));
        jTable_VeDaChon.setShowVerticalLines(false);
        jTable_VeDaChon.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTable_VeDaChon);

        jLabel_VeDaChon.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel_VeDaChon.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_VeDaChon.setText("Vé đã chọn");

        jButton_HoanTatHoaDon.setBackground(new java.awt.Color(255, 77, 77));
        jButton_HoanTatHoaDon.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jButton_HoanTatHoaDon.setForeground(new java.awt.Color(255, 255, 255));
        jButton_HoanTatHoaDon.setText("Hoàn Tất");
        jButton_HoanTatHoaDon.setBorderPainted(false);
        jButton_HoanTatHoaDon.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton_HoanTatHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_HoanTatHoaDonActionPerformed(evt);
            }
        });

        jButton_ThoatGiaoDienHoaDon.setBackground(new java.awt.Color(0, 102, 102));
        jButton_ThoatGiaoDienHoaDon.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jButton_ThoatGiaoDienHoaDon.setForeground(new java.awt.Color(255, 255, 255));
        jButton_ThoatGiaoDienHoaDon.setText("Quay Lại");
        jButton_ThoatGiaoDienHoaDon.setBorderPainted(false);
        jButton_ThoatGiaoDienHoaDon.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton_ThoatGiaoDienHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ThoatGiaoDienHoaDonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_VeDaChon)
                            .addComponent(jLabel_ChuyenBayDaChon)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel_NgayXuatHoaDon)
                                            .addComponent(jLabel_SoDienThoaiKhachHang)
                                            .addComponent(jLabel_TenKhachHang))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jDateChooser_NgayXuatHoaDon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                                            .addComponent(jTextField_SoDienThoaiKhachHang, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jTextField_TenKhachHang, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addGap(278, 278, 278)
                                        .addComponent(jTextField_TongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 789, Short.MAX_VALUE)
                                    .addComponent(jScrollPane1)
                                    .addComponent(jSeparator3)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jButton_ThoatGiaoDienHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButton_HoanTatHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel_TongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(39, 39, 39)
                                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                                        .addComponent(jLabel_PhoThong)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jTextField_SLVePhoThong, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                                        .addComponent(jLabel_ThuongGia)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(jTextField_SLVeThuongGia, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(jTextField_GiaVeThuongGia, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(jTextField_GiaVePhoThong, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))))))))
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(236, 236, 236))))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jTextField_SLVePhoThong, jTextField_SLVeThuongGia});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_ChuyenBayDaChon)
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_VeDaChon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_PhoThong)
                            .addComponent(jTextField_SLVePhoThong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(jTextField_GiaVePhoThong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_ThuongGia)
                            .addComponent(jTextField_SLVeThuongGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_GiaVeThuongGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_TongTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_TongTien)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_NgayXuatHoaDon)
                            .addComponent(jDateChooser_NgayXuatHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField_SoDienThoaiKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel_SoDienThoaiKhachHang))
                                .addGap(47, 47, 47))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextField_TenKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel_TenKhachHang)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_HoanTatHoaDon)
                    .addComponent(jButton_ThoatGiaoDienHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton_HoanTatHoaDon, jButton_ThoatGiaoDienHoaDon});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_ThoatGiaoDienHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ThoatGiaoDienHoaDonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton_ThoatGiaoDienHoaDonActionPerformed

    private void jButton_HoanTatHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_HoanTatHoaDonActionPerformed
        // TODO add your handling code here:
        HoaDon hoaDon = new HoaDon();
        hoaDon.setMaHoaDon(this.maHoaDon);
        hoaDon.setSdtKhachHang("123");
        String date = new SimpleDateFormat("yyyy-MM-dd").format(jDateChooser_NgayXuatHoaDon.getDate());
        System.out.println(date);
        java.util.Date dateDeParse=null;
        try {
            dateDeParse = new SimpleDateFormat("yyyy-MM-dd").parse(date);
        } catch (ParseException ex) {
            Logger.getLogger(GiaoDienHoaDonMotChieu.class.getName()).log(Level.SEVERE, null, ex);
        }
        java.sql.Date ngayXuatHoaDon = new java.sql.Date(dateDeParse.getTime());
        try {
            hoaDon.setNgayXuatHoaDon(ngayXuatHoaDon);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        hoaDon.setTrangThaiThanhToan(Byte.MIN_VALUE);
        hoaDon.setTongTien(this.tongTien);
        hoaDon.setSdtNhanVien("666");

        for(Ve ve : this.danhSachVe){
            ve.setMaHoaDon(hoaDon.getMaHoaDon());
        }
        
        InsertData.insertHoaDon(hoaDon);
        InsertData.insertVe(danhSachVe);
        
    }//GEN-LAST:event_jButton_HoanTatHoaDonActionPerformed
    
    
    private void hienThongTin() {
        new LoadData();
        int index = 0;
        for (ChuyenBay cb : controller.Controller.arrayListChuyenBay) {
            if (cb.getMaChuyenBay().equals(this.maChuyenBayDi)) {
                dtm2.addRow(new Object[]{
                    cb.getMaChuyenBay(), cb.getMaMayBay(), cb.getMaSanBayDi(), cb.getMaSanBayDen(), new SimpleDateFormat("dd/MM/yyyy").format(cb.getNgayBay()),
                    cb.getGioBay(), cb.getGhiChu(), cb.getKhoangCach()
                });
                index = controller.Controller.arrayListChuyenBay.indexOf(cb);
                this.giaCoBan = cb.getKhoangCach() * 500;
            }
        }
        for (Ve v : this.danhSachVe) {
            for (Ghe g : controller.Controller.arrayListChuyenBay.get(index).getArrayListGhe()) {
                if (v.getMaGhe().equalsIgnoreCase(g.getMaGhe())) {
                    if (g.getLoaiGhe().equalsIgnoreCase("PhoThong")) {
                        this.soVePhoThong++;
                        v.setGia(this.giaCoBan);
                    }
                    if (g.getLoaiGhe().equalsIgnoreCase("ThuongGia")) {
                        this.soVeThuongGia++;
                        v.setGia(giaCoBan * phanTramGiaThuongGia);
                    }
                }
            }
            dtm.addRow(new Object[]{
                v.getMaVe(), v.getSdtKhachHang(), v.getMaChuyenBay(), v.getGia(), v.getKyGui(), v.getTrangThaiDoi(),
                v.getTrangThaiVe(), v.getCmndNguoiBay(), v.getTenNguoiBay(), v.getEmailNguoiBay(), v.getSdtNguoiBay(),
                v.getMaHoaDon(), v.getMaGhe()
            });
        }

        jTextField_SLVePhoThong.setText("" + soVePhoThong);
        jTextField_SLVeThuongGia.setText("" + soVeThuongGia);
        jTextField_GiaVePhoThong.setText("" + giaCoBan);
        jTextField_GiaVeThuongGia.setText("" + giaCoBan * phanTramGiaThuongGia);
        this.tongTien = soVePhoThong * giaCoBan + soVeThuongGia * giaCoBan * phanTramGiaThuongGia;
        jTextField_TongTien.setText("" + tongTien);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GiaoDienHoaDonMotChieu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GiaoDienHoaDonMotChieu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GiaoDienHoaDonMotChieu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GiaoDienHoaDonMotChieu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                String[] danhSachMaVe = {"V01", "V02"};
                ArrayList<Ve> danhSachVe = new ArrayList<>();
                String maChuyenBayDi = "CB01";
                String maHoaDon = "HD01";

                Ve v1 = new Ve();
                v1.setKyGui((short) 20);
                v1.setMaVe("V01");
                v1.setCmndNguoiBay("CMNDNgu");
                v1.setMaChuyenBay("CB01");
                v1.setMaHoaDon(maHoaDon);
                v1.setMaGhe("A01-CB01");
                v1.setEmailNguoiBay("emai1");
                v1.setTrangThaiDoi((byte) 0);
                v1.setTrangThaiVe((byte) 0);
                v1.setSdtKhachHang("123");
                v1.setGia(0);
                v1.setTenNguoiBay("ten n");
                v1.setSdtNguoiBay("123");

                Ve v2 = new Ve();
                v2.setKyGui((short) 20);
                v2.setMaVe("V02");
                v2.setCmndNguoiBay("CMNDNgu");
                v2.setMaChuyenBay("CB01");
                v2.setMaHoaDon(maHoaDon);
                v2.setMaGhe("A02-CB01");
                v2.setEmailNguoiBay("emailNo");
                v2.setTrangThaiDoi((byte) 0);
                v2.setTrangThaiVe((byte) 0);
                v2.setSdtKhachHang("123");
                v2.setGia(0);
                v2.setTenNguoiBay("ten ngu2");
                v2.setSdtNguoiBay("223");

                danhSachVe.add(v1);
                danhSachVe.add(v2);

                for (Ve v : danhSachVe) {
                    System.out.println(v.toString());
                }
                new GiaoDienHoaDonMotChieu(maHoaDon, danhSachVe,
                        maChuyenBayDi).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_HoanTatHoaDon;
    private javax.swing.JButton jButton_ThoatGiaoDienHoaDon;
    private com.toedter.calendar.JDateChooser jDateChooser_NgayXuatHoaDon;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel_AirLines;
    private javax.swing.JLabel jLabel_ChuyenBayDaChon;
    private javax.swing.JLabel jLabel_HPT;
    private javax.swing.JLabel jLabel_IconMayBay;
    private javax.swing.JLabel jLabel_NgayXuatHoaDon;
    private javax.swing.JLabel jLabel_PhoThong;
    private javax.swing.JLabel jLabel_SoDienThoaiKhachHang;
    private javax.swing.JLabel jLabel_TenKhachHang;
    private javax.swing.JLabel jLabel_ThuongGia;
    private javax.swing.JLabel jLabel_TongTien;
    private javax.swing.JLabel jLabel_VeDaChon;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTable_ChuyenBayDaChon;
    private javax.swing.JTable jTable_VeDaChon;
    private javax.swing.JTextField jTextField_GiaVePhoThong;
    private javax.swing.JTextField jTextField_GiaVeThuongGia;
    private javax.swing.JTextField jTextField_SLVePhoThong;
    private javax.swing.JTextField jTextField_SLVeThuongGia;
    private javax.swing.JTextField jTextField_SoDienThoaiKhachHang;
    private javax.swing.JTextField jTextField_TenKhachHang;
    private javax.swing.JTextField jTextField_TongTien;
    // End of variables declaration//GEN-END:variables
}
