/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author t0168
 */
public class GiaoDienHoaDon extends javax.swing.JFrame {

    /**
     * Creates new form BillFrame
     */
    public GiaoDienHoaDon() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_Header = new javax.swing.JPanel();
        jLabel_IconMayBay = new javax.swing.JLabel();
        jLabel_HPT = new javax.swing.JLabel();
        jLabel_AirLines = new javax.swing.JLabel();
        jPanel_Container = new javax.swing.JPanel();
        jLabel_MaKhachHang = new javax.swing.JLabel();
        jTextField_MaKhachHang = new javax.swing.JTextField();
        jLabel_TenKhachHang = new javax.swing.JLabel();
        jTextField_TenKhachHang = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_ChuyenBayDaChon = new javax.swing.JTable();
        jLabel_ChuyenBayDaChon = new javax.swing.JLabel();
        jLabel_PhoThong = new javax.swing.JLabel();
        jTextField_SLVePhoThong = new javax.swing.JTextField();
        jLabel_ThuongGia = new javax.swing.JLabel();
        jTextField_SLVeThuongGia = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField_GiaVePhoThong = new javax.swing.JTextField();
        jTextField_GiaVeThuongGia = new javax.swing.JTextField();
        jLabel_NgayXuatHoaDon = new javax.swing.JLabel();
        jDateChooser_NgayXuatHoaDon = new com.toedter.calendar.JDateChooser();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField_TongTien = new javax.swing.JTextField();
        jLabel_TongTien = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_VeDaChon = new javax.swing.JTable();
        jLabel_VeDaChon = new javax.swing.JLabel();
        jButton_HoanTatHoaDon = new javax.swing.JButton();
        jButton_ThoatGiaoDienHoaDon = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel_Header.setBackground(new java.awt.Color(48, 57, 82));
        jPanel_Header.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jLabel_IconMayBay.setForeground(new java.awt.Color(204, 255, 255));
        jLabel_IconMayBay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/icons8_airplane_48px_4.png"))); // NOI18N

        jLabel_HPT.setFont(new java.awt.Font("Roboto Mono Light", 1, 48)); // NOI18N
        jLabel_HPT.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_HPT.setText("HPT");

        jLabel_AirLines.setFont(new java.awt.Font("Roboto Light", 1, 24)); // NOI18N
        jLabel_AirLines.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_AirLines.setText("AIRLINES™");

        javax.swing.GroupLayout jPanel_HeaderLayout = new javax.swing.GroupLayout(jPanel_Header);
        jPanel_Header.setLayout(jPanel_HeaderLayout);
        jPanel_HeaderLayout.setHorizontalGroup(
            jPanel_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_HeaderLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel_IconMayBay)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel_HPT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_AirLines, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_HeaderLayout.setVerticalGroup(
            jPanel_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_HeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel_HPT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel_AirLines, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel_IconMayBay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel_Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 722, -1));

        jPanel_Container.setBackground(new java.awt.Color(89, 98, 117));
        jPanel_Container.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jLabel_MaKhachHang.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel_MaKhachHang.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_MaKhachHang.setText("Mã Khách Hàng");

        jTextField_MaKhachHang.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N

        jLabel_TenKhachHang.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel_TenKhachHang.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_TenKhachHang.setText("Tên Khách Hàng");

        jTextField_TenKhachHang.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N

        jTable_ChuyenBayDaChon.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jTable_ChuyenBayDaChon.setForeground(new java.awt.Color(255, 255, 255));
        jTable_ChuyenBayDaChon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable_ChuyenBayDaChon.setGridColor(new java.awt.Color(0, 0, 0));
        jTable_ChuyenBayDaChon.setIntercellSpacing(new java.awt.Dimension(0, 0));
        jTable_ChuyenBayDaChon.setRowHeight(30);
        jTable_ChuyenBayDaChon.setSelectionBackground(new java.awt.Color(255, 77, 77));
        jTable_ChuyenBayDaChon.setShowVerticalLines(false);
        jTable_ChuyenBayDaChon.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable_ChuyenBayDaChon);

        jLabel_ChuyenBayDaChon.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel_ChuyenBayDaChon.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_ChuyenBayDaChon.setText("Chuyến bay đã chọn");

        jLabel_PhoThong.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel_PhoThong.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_PhoThong.setText("Phổ thông");

        jTextField_SLVePhoThong.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N

        jLabel_ThuongGia.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel_ThuongGia.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_ThuongGia.setText("Thương gia");

        jTextField_SLVeThuongGia.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("x");

        jLabel11.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("x");

        jTextField_GiaVePhoThong.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N

        jTextField_GiaVeThuongGia.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N

        jLabel_NgayXuatHoaDon.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel_NgayXuatHoaDon.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_NgayXuatHoaDon.setText("Ngày xuất hóa đơn");

        jLabel13.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("+");

        jLabel14.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("=");

        jTextField_TongTien.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N

        jLabel_TongTien.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel_TongTien.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_TongTien.setText("Tổng tiền");

        jTable_VeDaChon.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jTable_VeDaChon.setForeground(new java.awt.Color(255, 255, 255));
        jTable_VeDaChon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable_VeDaChon.setGridColor(new java.awt.Color(0, 0, 0));
        jTable_VeDaChon.setIntercellSpacing(new java.awt.Dimension(0, 0));
        jTable_VeDaChon.setRowHeight(30);
        jTable_VeDaChon.setSelectionBackground(new java.awt.Color(255, 77, 77));
        jTable_VeDaChon.setShowVerticalLines(false);
        jTable_VeDaChon.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTable_VeDaChon);

        jLabel_VeDaChon.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel_VeDaChon.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_VeDaChon.setText("Vé đã chọn");

        jButton_HoanTatHoaDon.setBackground(new java.awt.Color(255, 77, 77));
        jButton_HoanTatHoaDon.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jButton_HoanTatHoaDon.setForeground(new java.awt.Color(255, 255, 255));
        jButton_HoanTatHoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/icons8_forward_30px.png"))); // NOI18N
        jButton_HoanTatHoaDon.setText("Hoàn Tất");
        jButton_HoanTatHoaDon.setBorderPainted(false);
        jButton_HoanTatHoaDon.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        jButton_ThoatGiaoDienHoaDon.setBackground(new java.awt.Color(0, 102, 102));
        jButton_ThoatGiaoDienHoaDon.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jButton_ThoatGiaoDienHoaDon.setForeground(new java.awt.Color(255, 255, 255));
        jButton_ThoatGiaoDienHoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/icons8_back_30px.png"))); // NOI18N
        jButton_ThoatGiaoDienHoaDon.setText("Quay Lại");
        jButton_ThoatGiaoDienHoaDon.setBorderPainted(false);
        jButton_ThoatGiaoDienHoaDon.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout jPanel_ContainerLayout = new javax.swing.GroupLayout(jPanel_Container);
        jPanel_Container.setLayout(jPanel_ContainerLayout);
        jPanel_ContainerLayout.setHorizontalGroup(
            jPanel_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_ContainerLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(jPanel_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_ThoatGiaoDienHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel_VeDaChon)
                        .addGroup(jPanel_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel_ChuyenBayDaChon)
                            .addGroup(jPanel_ContainerLayout.createSequentialGroup()
                                .addGroup(jPanel_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel_ContainerLayout.createSequentialGroup()
                                        .addGroup(jPanel_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel_TenKhachHang)
                                            .addComponent(jLabel_MaKhachHang))
                                        .addGroup(jPanel_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel_ContainerLayout.createSequentialGroup()
                                                .addGap(33, 33, 33)
                                                .addComponent(jTextField_MaKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_ContainerLayout.createSequentialGroup()
                                                .addGap(34, 34, 34)
                                                .addComponent(jTextField_TenKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(88, 88, 88))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_ContainerLayout.createSequentialGroup()
                                        .addComponent(jLabel_NgayXuatHoaDon)
                                        .addGap(18, 18, 18)
                                        .addComponent(jDateChooser_NgayXuatHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(89, 89, 89)))
                                .addGroup(jPanel_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel_ContainerLayout.createSequentialGroup()
                                        .addComponent(jLabel_ThuongGia)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextField_SLVeThuongGia, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(jTextField_GiaVeThuongGia, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_ContainerLayout.createSequentialGroup()
                                            .addComponent(jLabel_TongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(35, 35, 35)
                                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jTextField_TongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_ContainerLayout.createSequentialGroup()
                                            .addGroup(jPanel_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(jPanel_ContainerLayout.createSequentialGroup()
                                                    .addComponent(jLabel_PhoThong)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                                                    .addComponent(jTextField_SLVePhoThong, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jTextField_GiaVePhoThong, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(jScrollPane1)
                            .addComponent(jSeparator3)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton_HoanTatHoaDon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(27, 27, 27))
        );

        jPanel_ContainerLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jTextField_SLVePhoThong, jTextField_SLVeThuongGia});

        jPanel_ContainerLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jTextField_GiaVePhoThong, jTextField_GiaVeThuongGia, jTextField_TongTien});

        jPanel_ContainerLayout.setVerticalGroup(
            jPanel_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ContainerLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel_ChuyenBayDaChon)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_VeDaChon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(jPanel_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_ContainerLayout.createSequentialGroup()
                        .addGroup(jPanel_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_PhoThong)
                            .addComponent(jTextField_SLVePhoThong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(jTextField_GiaVePhoThong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)
                        .addGap(7, 7, 7)
                        .addGroup(jPanel_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_ThuongGia)
                            .addComponent(jTextField_SLVeThuongGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_GiaVeThuongGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_TongTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_TongTien)))
                    .addGroup(jPanel_ContainerLayout.createSequentialGroup()
                        .addGroup(jPanel_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_NgayXuatHoaDon)
                            .addComponent(jDateChooser_NgayXuatHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_ContainerLayout.createSequentialGroup()
                                .addGroup(jPanel_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_MaKhachHang)
                                    .addComponent(jTextField_MaKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(47, 47, 47))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextField_TenKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel_TenKhachHang)))))
                .addGap(18, 18, 18)
                .addGroup(jPanel_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_ThoatGiaoDienHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_HoanTatHoaDon))
                .addGap(24, 24, 24))
        );

        jPanel_ContainerLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton_HoanTatHoaDon, jButton_ThoatGiaoDienHoaDon});

        jPanel_ContainerLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jDateChooser_NgayXuatHoaDon, jTextField_MaKhachHang});

        getContentPane().add(jPanel_Container, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, -1, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GiaoDienHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GiaoDienHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GiaoDienHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GiaoDienHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GiaoDienHoaDon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_HoanTatHoaDon;
    private javax.swing.JButton jButton_ThoatGiaoDienHoaDon;
    private com.toedter.calendar.JDateChooser jDateChooser_NgayXuatHoaDon;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel_AirLines;
    private javax.swing.JLabel jLabel_ChuyenBayDaChon;
    private javax.swing.JLabel jLabel_HPT;
    private javax.swing.JLabel jLabel_IconMayBay;
    private javax.swing.JLabel jLabel_MaKhachHang;
    private javax.swing.JLabel jLabel_NgayXuatHoaDon;
    private javax.swing.JLabel jLabel_PhoThong;
    private javax.swing.JLabel jLabel_TenKhachHang;
    private javax.swing.JLabel jLabel_ThuongGia;
    private javax.swing.JLabel jLabel_TongTien;
    private javax.swing.JLabel jLabel_VeDaChon;
    private javax.swing.JPanel jPanel_Container;
    private javax.swing.JPanel jPanel_Header;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTable_ChuyenBayDaChon;
    private javax.swing.JTable jTable_VeDaChon;
    private javax.swing.JTextField jTextField_GiaVePhoThong;
    private javax.swing.JTextField jTextField_GiaVeThuongGia;
    private javax.swing.JTextField jTextField_MaKhachHang;
    private javax.swing.JTextField jTextField_SLVePhoThong;
    private javax.swing.JTextField jTextField_SLVeThuongGia;
    private javax.swing.JTextField jTextField_TenKhachHang;
    private javax.swing.JTextField jTextField_TongTien;
    // End of variables declaration//GEN-END:variables
}
